spring:
  freemarker:
    template-loader-path:
    - /templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    request-context-attribute: request
    expose-request-attributes: false
    expose-session-attributes: false
    suffix: .ftl